  const constData = {
  neighborhoods: [
    "Abell",
    "Allendale",
    "Arcadia",
    "Arlington",
    "Armistead Gardens",
    "Ashburton",
    "Baltimore Highlands",
    "Patterson Park Neighborhood",
    "Barclay",
    "Barre Circle",
    "Beechfield",
    "Belair-Parkside",
    "Bellona-Gittings",
    "Berea",
    "Better Waverly",
    "Beverly Hills",
    "Biddle Street",
    "Blythewood",
    "Bolton Hill",
    "Boyd-Booth",
    "Brewers Hill",
    "Bridgeview/Greenlawn",
    "Broadway East",
    "Broening Manor",
    "Brooklyn",
    "Burleith-Leighton",
    "Butcher's Hill",
    "Callaway-Garrison",
    "Cameron Village",
    "Canton",
    "Canton Industrial Area",
    "Carroll - Camden Industrial Area",
    "Carroll Park",
    "Carroll-South Hilton",
    "Carrollton Ridge",
    "Cedarcroft",
    "Cedmont",
    "Cedonia",
    "Central Forest Park",
    "Central Park Heights",
    "Charles North",
    "Cherry Hill",
    "Cheswolde",
    "Chinquapin Park",
    "Orchard Ridge",
    "Clifton Park",
    "Coldspring",
    "Coldstream Homestead Montebello",
    "Concerned Citizens Of Forest Park",
    "Coppin Heights/Ash-Co-East",
    "Cross Country",
    "Cross Keys",
    "Curtis Bay",
    "Curtis Bay Industrial Area",
    "Cylburn",
    "Darley Park",
    "Dickeyville",
    "Dolfield",
    "Dorchester",
    "Downtown",
    "Druid Heights",
    "Druid Hill Park",
    "Dunbar-Broadway",
    "Dundalk Marine Terminal",
    "East Arlington",
    "East Baltimore Midway",
    "Easterwood",
    "Eastwood",
    "Edmondson Village",
    "Ednor Gardens-Lakeside",
    "Ellwood Park/Monument",
    "Evergreen",
    "Evergreen Lawn",
    "Fairfield Area",
    "Fairmont",
    "Fallstaff",
    "Federal Hill",
    "Fells Point",
    "Forest Park",
    "Forest Park Golf Course",
    "Frankford",
    "Franklin Square",
    "Franklintown",
    "Franklintown Road",
    "Garwyn Oaks",
    "Gay Street",
    "Glen",
    "Glen Oaks",
    "Glenham-Belhar",
    "Graceland Park",
    "Greektown",
    "Greenmount Cemetery",
    "Greenmount West",
    "Greenspring",
    "Grove Park",
    "Guilford",
    "Gwynns Falls",
    "Gwynns Falls/Leakin Park",
    "Hampden",
    "Hanlon-Longwood",
    "Hamilton Hills",
    "Harlem Park",
    "Harwood",
    "Hawkins Point",
    "Heritage Crossing",
    "Herring Run Park",
    "Highlandtown",
    "Hillen",
    "Hoes Heights",
    "Holabird Industrial Park",
    "Hollins Market",
    "Homeland",
    "Hopkins Bayview",
    "Howard Park",
    "Hunting Ridge",
    "Idlewood",
    "Inner Harbor",
    "Irvington",
    "Johns Hopkins Homewood",
    "Johnston Square",
    "Jones Falls Area",
    "Jonestown",
    "Bayview",
    "Kenilworth Park",
    "Kernewood",
    "Keswick",
    "Kresson",
    "Lake Evesham",
    "Lake Walker",
    "Lakeland",
    "Langston Hughes",
    "Lauraville",
    "Levindale",
    "Liberty Square",
    "Little Italy",
    "Loch Raven",
    "Locust Point",
    "Locust Point Industrial Area",
    "Lower Herring Run Park",
    "Loyola/Notre Dame",
    "Lucille Park",
    "Madison Park",
    "Madison-Eastend",
    "Mayfield",
    "McElderry Park",
    "Medfield",
    "Medford",
    "Mid-Govans",
    "Mid-Town Belvedere",
    "Middle Branch/Reedbird Parks",
    "Middle East",
    "Midtown-Edmondson",
    "Millhill",
    "Milton-Montford",
    "Mondawmin",
    "Montebello",
    "Moravia-Walther",
    "Morgan Park",
    "Morgan State University",
    "Morrell Park",
    "Mosher",
    "New Southwest/Mount Clare",
    "Mount Holly",
    "Mount Vernon",
    "Mount Washington",
    "Mount Winans",
    "Mt Pleasant Park",
    "New Northwood",
    "North Harford Road",
    "North Roland Park/Poplar Hill",
    "Northwest Community Action",
    "O'Donnell Heights",
    "Oakenshawe",
    "Oaklee",
    "Oldtown",
    "Oliver",
    "Orangeville",
    "Orangeville Industrial Area",
    "Original Northwood",
    "Otterbein",
    "Overlea",
    "Panway/Braddish Avenue",
    "Park Circle",
    "Parklane",
    "Parkside",
    "Parkview/Woodbrook",
    "Patterson Park",
    "Patterson Place",
    "Pen Lucy",
    "Penn North",
    "Penn-Fallsway",
    "Penrose/Fayette Street Outreach",
    "Perkins Homes",
    "Perring Loch",
    "Pimlico Good Neighbors",
    "Pleasant View Gardens",
    "Poppleton",
    "Port Covington",
    "Pulaski Industrial Area",
    "Purnell",
    "Radnor-Winston",
    "Ramblewood",
    "Reisterstown Station",
    "Remington",
    "Reservoir Hill",
    "Richnor Springs",
    "Ridgely's Delight",
    "Riverside",
    "Rognel Heights",
    "Roland Park",
    "Rosebank",
    "Rosemont",
    "Rosemont East",
    "Rosemont Homeowners/Tenants",
    "Sabina-Mattfeldt",
    "Saint Agnes",
    "Saint Helena",
    "Saint Josephs",
    "Saint Paul",
    "Sandtown-Winchester",
    "South Baltimore",
    "Seton Business Park",
    "Seton Hill",
    "Sharp-Leadenhall",
    "Shipley Hill",
    "South Clifton Park",
    "Spring Garden Industrial Area",
    "Stadium Area",
    "Stonewood-Pentwood-Winston",
    "Taylor Heights",
    "Ten Hills",
    "The Orchards",
    "Towanda-Grantley",
    "Tremont",
    "Tuscany-Canterbury",
    "Union Square",
    "University Of Maryland",
    "Uplands",
    "Upper Fells Point",
    "Upton",
    "Villages Of Homeland",
    "Violetville",
    "Wakefield",
    "Walbrook",
    "Waltherson",
    "Washington Hill",
    "Washington Village/Pigtown",
    "Waverly",
    "West Arlington",
    "West Forest Park",
    "West Hills",
    "Westfield",
    "Westgate",
    "Westport",
    "Wilson Park",
    "Winchester",
    "Windsor Hills",
    "Winston-Govans",
    "Woodberry",
    "Woodbourne Heights",
    "Woodbourne-McCabe",
    "Woodmere",
    "Wyman Park",
    "Wyndhurst",
    "Yale Heights",
    "Lower Edmondson Village",
    "Wilhelm Park",
    "Edgewood",
    "Evesham Park",
    "Belvedere",
    "Wrenlane",
    "York-Homeland",
    "CARE",
    "Downtown West",
    "Belair-Edison",
    "Four By Four",
    "Charles Village",
    "Old Goucher",
  ],
  crimeCodes: {
     "AGG. ASSAULT": "#E74C3C" ,
     "ARSON": "#8E44AD" ,
     "AUTO THEFT": "#2980B9" ,
     "BURGLARY": "#1ABC9C" ,
     "COMMON ASSAULT": "#FFBF00" ,
     "HOMICIDE": "#D35400" ,
     "LARCENY": "#34495E" ,
     "LARCENY FROM AUTO": "#7209b7" ,
     "RAPE": "#3a0ca3" ,
     "ROBBERY - CARJACKING": "#ff6d00" ,
     "ROBBERY - COMMERCIAL": "#008000" ,
     "ROBBERY - RESIDENCE": "#ccff33" ,
     "ROBBERY - STREET": "#ff5d8f" ,
     "SHOOTING": "#11151c" ,
  }
};

export default constData;
